booksporium_project/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf.urls.static import static
from django.conf import settings
from django.conf.urls import url
from django.views.static import serve

urlpatterns = [
    path('admin/', admin.site.urls),
    path("",include('accounts.urls')),
    url(r'^download/(?P<path>.*)$',serve,{'document_root':settings.MEDIA_ROOT}),
    url(r'^media/(?P<path>.*)$', serve,{'document_root':       settings.MEDIA_ROOT}), 
    url(r'^static/(?P<path>.*)$', serve,{'document_root': settings.STATIC_ROOT}), 
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

posts/urls.py
from django.urls import path, include
from . import views

urlpatterns = [
    # path("",views.afterSignin, name = "afterSignin"),
    # path("",views.homePage, name = "home_page"),
    # path("index/",views.homePage,name = "home_page"),
    path("",views.postBookAD, name = "post_book_ad"),
    path("afterPost/",views.submitPost, name = "afterPost")
]

accounts/models.py
from django.db import models

# Create your models here.

class Users(models.Model):
    full_name = models.CharField(max_length=100)
    email = models.CharField(max_length=100, primary_key = True)
    password = models.CharField(max_length=100)
    phone_no = models.CharField(max_length=12)

    def __str__(self):
        return self.email

class BookstoreSeller(models.Model):
    store_name = models.CharField(max_length=100)
    seller_name = models.CharField(max_length=100)
    email = models.CharField(max_length=100, primary_key = True)
    password = models.CharField(max_length=100)
    phone_no = models.CharField(max_length=12)
    
    def __str__(self):
        return self.email

# Book post
class BookStoreAd(models.Model):
    bookStoreSeller = models.ForeignKey(to=BookstoreSeller, on_delete=models.CASCADE)
    bookStore_name = models.CharField(max_length=100)
    topic_book = models.CharField(max_length=100)
    description = models.TextField()
    image_1 = models.ImageField()
    state = models.CharField(max_length=100)
    city = models.CharField(max_length=100)
    area = models.CharField(max_length=100)
    upload_date = models.DateTimeField(auto_now=False, auto_now_add=True)

    def __str__(self):
        return self.bookStoreSeller.email

class MessageByChat(models.Model):
    sender = models.ForeignKey(to = Users, on_delete=models.CASCADE, related_name='sender')
    receiver = models.ForeignKey(to = Users, on_delete=models.CASCADE, related_name='receiver')
    message = models.CharField(max_length=1200)
    timestamp = models.DateTimeField(auto_now_add=True)
    is_read = models.BooleanField(default=False)

    def __str__(self):
        return self.message

    class Meta:
        ordering = ('timestamp',)

class UserImage(models.Model):
    user = models.ForeignKey(to = Users, on_delete=models.CASCADE)
    image = models.ImageField()

    def __str__(self):
        return self.user.email

posts/models.py
from django.db import models
from accounts.models import *
# Create your models here.

# Book post
class BookAd(models.Model):
    seller = models.ForeignKey(to=Users, on_delete=models.CASCADE)
    book_name = models.CharField(max_length=100)
    book_author = models.CharField(max_length=100)
    book_price = models.FloatField()
    description = models.TextField()
    image_1 = models.ImageField()
    image_2 = models.ImageField()
    image_3 = models.ImageField()
    state = models.CharField(max_length=100)
    city = models.CharField(max_length=100)
    area = models.CharField(max_length=100)
    upload_date = models.DateTimeField(auto_now=False, auto_now_add=True)

    def __str__(self):
        return self.seller.email

posts/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.views import View
from .models import *
from accounts.models import *
from random import randint
from django.core.mail import send_mail
from django.conf import settings

# Create your views here.


# after Sign In Function
def afterSignin(request):
    if request.method == "POST":
        email = request.POST.get("email")
        try:
            Users.objects.get(email = email)
        except Exception as err:
            msg = "Email and Password is Wrong.."
            return render(request,"accounts/signin.html",{"error_msg": msg})
        else:
            user = Users.objects.get(email = email)
            if(user.password == request.POST.get("password")):
                # return HttpResponse("SuccessFully LogIn...")
                # return render(request,"post/home.html")
                return homePage(request)
            else:
                msg = "Email and Password is Wrong.."
                return render(request,"accounts/signin.html",{"error_msg": msg})

# home Page
def homePage(request):
    if request.session.get("email"):
        return render(request,"post/home.html")

# create Book Post Ad
def postBookAD(request):
    return render(request,"post/post_book.html")

def submitPost(request):
    if request.method == "POST":
        book_detail = {
            "seller": Users.objects.get(email = request.session.get("email")),
            "book_name": request.POST.get("book_name"),
            "book_author": request.POST.get("book_author_name"),
            "book_price": float(request.POST.get("book_price")),
            "description": request.POST.get("book_desc"),
            "image_1": request.POST.get("image_1"),
            "image_2": request.POST.get("image_2"),
            "image_3": request.POST.get("image_3"),
            "state": request.POST.get("state"),
            "city": request.POST.get("city"),
            "area": request.POST.get("area")
        }
        print(book_detail)
        BookAd.objects.create(**book_detail)
        # return render(request,"post/home.html")
        return redirect("homePage")

templates/post/chat_app_2.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>BookSporium</title>
    <link rel="stylesheet" href="{% static 'css/book_show.css' %}">
    <link rel="stylesheet" href="{% static 'css/footer.css' %}">
    <link rel="stylesheet" href="{% static 'css/chat_app.css' %}">
    <script src="https://kit.fontawesome.com/152ca9cf76.js" crossorigin="anonymous"></script>
</head>

<body>

    <!-- Header Part -->
    <header>
        <div class="upper-header">
            <div class="overlay">
                <div class="container">
                    <nav>
                        <div class="logo">
                            <a href="{% url 'homePage' %}">
                            <img src="{% static 'images/BOOKSPORIUM.png' %}" alt="Booksporium_Logo"></a>
                        </div>
                        <div class="mid-title">
                            <form action="" id="search">
                                <i class="fas fa-map-marker-alt location_icon"></i>
                                <select name="location" id="location">
                                    <option value="ranip">Ranip</option>
                                    <option value="bodakdev">Bodakdev</option>
                                    <option value="sabarmati">Sabarmati</option>
                                    <option value="vadaj">Vadaj</option>
                                    <option value="shastri Nager">Shastri Nager</option>
                                    <option value="nikol">Nikol</option>
                                </select>
                                <i class="fas fa-search search"></i>
                                <input type="text" name="search_name" id="search_name"
                                    placeholder="Search Any BookStore, Books, e-Book">
                            </form>
                        </div>
                        <div class="account" style="width: 260px;">
                            <a href="#"><i class="far fa-bell"></i></a>
                            <a href="{% url 'chat' %}"><i class="far fa-comments"></i></a>
                            <div class="user-click">
                                <a href="#" class="user-icon"><i class="fas fa-user-circle" id="user"></i></a>
                                <div class="user-option" id="box">
                                    <div class="profile-option">
                                        <div class="user-img">
                                            <i class="fas fa-user-circle"></i>
                                        </div>
                                        <div class="user-detail">
                                            <h3 class="user-name">Mihir Prajapati</h3>
                                            <a href="{% url 'profile' %}" class="edit-detail">View and Edit Profile</a>
                                        </div>
                                    </div>
                                    <div class="option">
                                        <div class="option-detail">
                                            <i class="fas fa-database"></i>
                                            <a href="{% url 'myads' %}" class="my-add">My Adds</a>
                                        </div>
                                        <div class="option-detail">
                                            <i class="far fa-address-card"></i>
                                            <a href="#" class="my-add">Buy Business Package</a>
                                        </div>
                                    </div>
                                    <div class="option">
                                        <div class="option-detail">
                                            <i class="far fa-address-card"></i>
                                            <a href="#" class="my-add">Help</a>
                                        </div>
                                        <div class="option-detail">
                                            <i class="fas fa-sliders-h"></i>
                                            <a href="#" class="my-add">Settings</a>
                                        </div>
                                    </div>
                                    <div class="option">
                                        <div class="option-detail">
                                            <i class="fas fa-sign-out-alt"></i>
                                            <a href="{% url 'logOut' %}" class="my-add">Logout</a>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <a href="{% url 'post_book_ad' %}" class="btn sell-btn">sell</a>
                        </div>
                    </nav>
                </div>
            </div>
        </div>
        <div class="lower-header">
            <div class="container">
                <ul class="nav-list">
                    <li><a href="/home_page/search_all/book_store" class="nav-link">Book Store</a></li>
                    <li>
                        <a href="#" class="nav-link">e-Book</a>
                        <div class="drop-down">
                            <div class="content">
                                <div class="row">
                                    <ul>
                                        <li><a href="/home_page/search/comic" class="nav-link">Comic</a></li>
                                        <li><a href="/home_page/search/adventure" class="nav-link">Adventure</a></li>
                                        <li><a href="/home_page/search/sci-fi" class="nav-link">Sci-Fi</a></li>
                                        <li><a href="/home_page/search/business" class="nav-link">Business</a></li>
                                        <li><a href="/home_page/search/programming" class="nav-link">Programming</a></li>
                                    </ul>
                                </div>
                                <div class="row">
                                    <ul>
                                        <li><a href="/home_page/search/horror" class="nav-link">Horror</a></li>
                                        <li><a href="/home_page/search/thriller" class="nav-link">Thriller</a></li>
                                        <li><a href="/home_page/search/kids" class="nav-link">Kids</a></li>
                                        <li><a href="/home_page/search/grammer" class="nav-link">Grammer</a></li>
                                        <li><a href="/home_page/search/design" class="nav-link">Design</a></li>
                                    </ul>
                                </div>
                                <div class="row">
                                    <ul>
                                        <li><a href="/home_page/search/GPSC" class="nav-link">UPSC/GPSC</a></li>
                                        <li><a href="/home_page/search/exam" class="nav-link">Goverment Exam</a></li>
                                        <li><a href="/home_page/search/bsc" class="nav-link">B.sc/M.sc</a></li>
                                        <li><a href="/home_page/search/bcom" class="nav-link">B.com/M.com</a></li>
                                        <li><a href="/home_page/search/arts" class="nav-link">Arts</a></li>
                                    </ul>
                                </div>
                                <div class="row">
                                    <ul>
                                        <li><a href="/home_page/search/be" class="nav-link">B.E/M.E</a></li>
                                        <li><a href="/home_page/search/school" class="nav-link">School</a></li>
                                        <li><a href="/home_page/search/science" class="nav-link">Science</a></li>
                                        <li><a href="/home_page/search/commerce" class="nav-link">Commerce</a></li>
                                    </ul>
                                </div>
                            </div>
                        </div>
                    </li>
                    <li><a href="/home_page/search_all/book" class="nav-link">Books</a></li>
                    <li><a href="#" class="nav-link">Rental Book</a></li>
                </ul>
            </div>
        </div>
    </header>

    <!-- chat app show -->
    <section class="chat-app">
        <div class="chat-container">
            <div class="chat-left">
                <div class="chat-user-account-show" id="{{ seller_detail.seller.email }}">
                    <div class="user-img">
                        <!-- <i class="fas fa-user-circle"></i> -->
                        <img src="{{ seller_detail.image_1.url }}" alt="">
                    </div>
                    <div class="user-name">
                        <h3 class="name">{{ seller_detail.full_name }}</h3>
                        <p class="last-msg">When a unknow took a print a book. hsbjbjdnknfnikanifneknk</p>
                    </div>
                    <div class="last-time">
                        <p class="time">9.23 AM</p>
                    </div>
                </div>
            </div>
            <div class="chat-right">
                <div class="user-head">
                    <div class="user-img">
                        <!-- <i class="fas fa-user-circle"></i> -->
                        <img src="{{ seller_detail.image_1.url }}" alt="">
                    </div>
                    <div class="user-name">
                        <h3 class="name">{{ seller_detail.full_name }}</h3>
                        <p class="last-msg">Online</p>
                    </div>
                    <div class="last-time">
                        <a href="#"><i class="fas fa-ellipsis-v"></i></a>
                    </div>
                </div>
                <div class="msg-show" id="board">
                    {% for message in messages %}
                    {% if message.sender == sender %}
                    <div class="actual_user right">
                        <p class="actual_user_msg">{{message.message}}</p>
                        <p class="actual_user_time">{{message.timestamp.time}}</p>
                    </div>
                    {% else %}
                    <div class="local_user left">
                        <p class="local_user_msg">{{message.message}}</p>
                        <p class="local_user_time">{{message.timestamp.time}}</p>
                    </div>
                    {% endif%}
                    {% endfor %}
                </div>
                <div class="msg-type">
                    <form  method="POST" action="message_save/" id="chat_box">
                        {% csrf_token %}
                        <div class="text-input">
                            <input type="text" id="id_message" name="message" class="user-msg" placeholder="Type a Message">
                            <a href="#"><i class="far fa-smile smile"></i></a>
                            <a href="#"><i class="far fa-image image"></i></a>
                            <input type="submit" class="send" value="Send">
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </section>

    <!-- Footer -->
    <footer>
        <div class="container">
            <div class="content">
                <div class="row">
                    <div class="logo">
                        <img src="{% static 'images/BOOKSPORIUM_footer.png' %}" alt="">
                    </div>
                    <h4>BookSporium is for Buy and earn Money by selling Your old Book.</h5>
                </div>
                <div class="row">
                    <h5 class="footer-title">About us</h5>
                    <ul>
                        <li><a href="#">Book, Magezin</a></li>
                        <li><a href="#">Sell any Book</a></li>
                        <li><a href="#">Download e-Book</a></li>
                        <li><a href="#">Rented Book</a></li>
                    </ul>
                </div>
                <div class="row">
                    <h5 class="footer-title">Contact us</h5>
                    <ul>
                        <li><a href="#">3/13 naman Street</a></li>
                        <li><a href="#">Borivali, mumbai</a></li>
                        <li><a href="#">Maharastra-45128</a></li>
                        <li><a href="#">123-154-7648</a></li>
                    </ul>
                </div>
                <div class="row">
                    <h5 class="footer-title">Follow us</h5>
                    <div class="social_icon">
                        <a href="#"><i id="fb" class="fab fa-facebook"></i></a>
                        <a href="#"><i id="instagram" class="fab fa-instagram"></i></a>
                        <a href="#"><i id="pinterest" class="fab fa-pinterest"></i></a>
                        <a href="#"><i id="twitter" class="fab fa-twitter"></i></a>
                    </div>
                </div>
            </div>
            <p id="copyright">Copyright &copy;: www.booksporium.com</p>
        </div>
    </footer>

    <script src="{% static 'js/profile.js' %}"></script>
    <script src="{% static 'js/post_book.js' %}"></script>
    <script>

        var text_box = `
            <div class="actual_user right">
                <p class="actual_user_msg">{{ message }}</p>
                <p class="actual_user_time">9:15 pm</p>
            </div>
        `;
    </script>
</body>

</html>